version: '2.0' 

services:

  api: 
    container_name: next-api
    build: ./backend
    ports:
      - "3000:3000"
    volumes: 
      - ./backend:/home/api
      - /home/api/node_modules
    depends_on:
      - database

  database: 
    image: postgres:latest
    container_name: next-db
    environment:
      POSTGRES_DB: next-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5445:5432"